#!/bin/sh

set -e

cd "$(dirname "$(readlink -f "$0")")"
if [ x"${USER}" = x"root" ]; then
    echo -n "user? "
    read USER
    getent passwd $USER || {
        echo "User $USER is unknown"
        exit 1
    }
    HOME=$(getent passwd $USER | awk -F: '{print $6}')
else
    SUDO=sudo
fi

for module in puppetlabs-apt jhoblitt-udev; do
    [ -d external-modules/${module#*-} ] || \
        puppet module \
        --confdir=$PWD \
        --modulepath=$PWD/external-modules \
        install $module
done

$SUDO env \
    FACTERLIB=$PWD/facts \
    FACTER_user=$USER \
    FACTER_home=$HOME \
  puppet apply \
    --confdir=$PWD \
    --modulepath=$PWD/external-modules:$PWD/modules:/usr/share/puppet/modules \
    "$@" \
    manifests/site.pp
