#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
[ x"${USER}" = x"root" ] || SUDO=sudo

for module in puppetlabs-apt jhoblitt-udev; do
    [ -d external-modules/${module#*-} ] || \
        puppet module \
        --confdir=$PWD \
        --modulepath=$PWD/external-modules \
        install $module
done

$SUDO env \
    FACTERLIB=$PWD/facts \
    FACTER_user=$USER \
    FACTER_home=$HOME \
  puppet apply \
    --confdir=$PWD \
    --modulepath=$PWD/external-modules:$PWD/modules:/usr/share/puppet/modules \
    "$@" \
    manifests/site.pp
