#!/bin/sh
# Invoke shell if build fails.

apt-get -qqy install mg less zsh wget ca-certificates
cd /tmp/buildd/*/debian/..
export TERM=xterm
wget -qO - https://vincentbernat-zshrc.s3.amazonaws.com/zsh-install.sh | sh
/bin/zsh < /dev/tty > /dev/tty 2> /dev/tty
