#!/bin/sh
# Invoke shell if build fails.

apt-get -qqy install mg less zsh wget ca-certificates sudo
echo "pbuilder ALL=(ALL:ALL) NOPASSWD:  ALL" > /etc/sudoers.d/pbuilder
chmod 0440 /etc/sudoers.d/pbuilder
cd /build/*/debian/..
export TERM=xterm
export HOME=/build
sudo -n -u pbuilder wget -qO - https://vincentbernat-zshrc.s3.amazonaws.com/zsh-install.sh | sudo -n -u pbuilder env HOME=$HOME sh
sudo -n -u pbuilder env HOME=$HOME PBUILDERPID=$PBUILDERPID /bin/zsh < /dev/tty > /dev/tty 2> /dev/tty
