#!/bin/sh
# Invoke shell if build fails.

apt-get -qqy install mg less zsh wget ca-certificates sudo
echo "pbuilder ALL=(ALL:ALL) NOPASSWD:  ALL" > /etc/sudoers.d/pbuilder
cd /build/*/debian/..
export TERM=xterm
export HOME=/home/pbuilder
mkdir -p $HOME
chown pbuilder:pbuilder $HOME
sudo -u pbuilder wget -qO - https://vincentbernat-zshrc.s3.amazonaws.com/zsh-install.sh | sudo -u pbuilder env HOME=$HOME sh
sudo -u pbuilder env HOME=$HOME PBUILDERPID=$PBUILDERPID /bin/zsh < /dev/tty > /dev/tty 2> /dev/tty
