#!/bin/sh

# http://git.hadrons.org/cgit/debian/gcc-on-diet.git/
# Sometimes, GCC is uploaded unstripped.
find /usr/lib/gcc/*/ /usr/libexec/gcc/*/ -maxdepth 2 -type f -size +10M -print0 \
    | xargs -r0 strip --strip-unneeded --remove-section=.comment --remove-section=.note \
    || true
